language: cpp

os:
  - linux
  - osx
  
compiler:
- clang
- gcc
  
before_install:
- sudo apt-get update -qq

install: 
- sudo apt-get install build-essential
- sudo apt-get install libc6-2.16-1 -y

script:

- git clone https://github.com/premake/premake-core.wiki.git premake
- cd premake
- make -f Bootstrap.mak $TRAVIS_OS_NAME
- mv premake/bin/release/premake5 ./extern/project/
 
- cd ./extern/project
- chmod a+x ./premake5
- ./premake5 gmake
- cd ../../
- cd serialisation
- make config=debug_x32
- make config=debug_x64
- make config=release_x32
- make config=release_x64
- make config=coverage_x32
- make config=coverage_x64

- cd ../bin/x32/
- ./serialisation-test
- ./serialisation-testd
- ./serialisation-testcd

- cd ../x64/
- ./serialisation-test
- ./serialisation-testd
- ./serialisation-testcd