sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=6
global:
  env:
  - PROJECT=SerLib
  - PROJECT_DIRECTORY=serialisation
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: v5bTqYYzKP5rhOxk1rlZ7YgVJ7UQA9MY/tNpb9j5A/7DMUyyTI6VqAI11qG8fmbWFjOjMYYJ1aVLR/ZMyYZ1KkHkUOHO4n+6BbEbdFmgRgx4HRGhr4xpWPt2CH9lk6B2rOEL8OFnLQo+WMJLKbcqhMt+6X8Axh0mh4ogx+zvscWorjKkiUf5Y9IbHbgiWigLDizdc7EJ88bLV/rangoEv1NeWS8kwq2T55QE2USd8B7X4wx8fTCjuiDEburSiFFjhSV1T/JLjjL/I1fOup5rf2F5oadJUBE20cvBODjOziGdKmeaarmJRQapsd4Zbcx1RONZEfzpGRHaCICtWjZ5/TKMRKi0qCKieQponQGdWWe1HVQt9DCKF1XP9pEXQ8UjVT3tRIhYjqtCJLG5uWGFWrqPEty3MxQM86QoWlcmWF9fNXc3GGB1tGOXHuuYHg4X93B/rq9WVzN3lVfqL85y3xgo305e4RMD8I3vcrHzKXsqoOVDIPw5hst2qkNqYoDTz7/O+iW+7vT9gtdnTmOJRVWtQp7poUU43vWordLTRlwHqf2/uEmBhS4l668bgK4YiUkqGIxVwV9baH22+1cd6yeWvD1lv8FqO5nsKA3804BNEiEyJ2iwkb+LA7Pid48FW3WbQfdQLxcfR4NayQ2nhhOztZRi1jDfZ1Gx6Ts/VpU=
